[package]
name = "yew-input"
version = "0.1.0"
authors = ["Noah <noah@coronasoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.17.2"
yew-state = "0.2.1"
web-sys = "0.3.42"
yewtil = "0.3.0"
